WIP: Divide github actions into multiple steps
agrc/skid pull request #26
Opened 2024-08-16 20:38 UTC by jacobdadams

The original template had a single action for testing and deploying to both dev and prod. Following the pattern just pushed to palletjack, this now has a single deploy composite action that is triggered on both pushes to dev (dev env) and releases (prod env). Pull requests trigger tests, and pushes to main trigger release PRs.

2024-08-16 22:40 UTC, steveoh commented on .github/workflows/push.yml
> -      - dev
i believe you still want these or you will have a lot of skipped/failed runs when the if conditions are unmet.

2024-08-16 22:57 UTC, steveoh commented on README.md
> +The cloud functions may need 512 MB or 1 GB of RAM to run successfully. The source dir should point to `src/skidname`. A cloud function just runs the specified function in the `main.py` file in the s
**question**: the skid dependencies, palletjack, supervisor, etc, don't require that memory right? I would guess that the amount of memory is directly related to the amount of rows and attributes in the data frames x 2 or 3 depending on how many are used in the pipeline. Is this close to accurate?

```suggestion
The cloud function will need the RAM size monitored to find the right size for the skid to run successfully. The `source_dir` should point to `src/skidname`. A cloud function runs the specified function in the `main.py` file based on the path in the `source_dir`; it doesn't pip install the function itself. It will pip install any dependencies listed in `src/skidname/requirements.txt`, however.
```

2024-08-16 22:59 UTC, steveoh commented on README.md
> +- Pushes to main (usually from merging a PR into main, but also direct pushes) will open a release PR to create a GitHub release with associated git tag and version bump.
```suggestion
- Pushes to main (usually from merging a PR into main, but also direct pushes) will open a release PR to create a GitHub release with an associated git tag and version bump if the commits pushed contain conventional commit types that trigger a release.
```

2024-08-16 23:02 UTC, steveoh commented on README.md
> +The actions rely on several GitHub secrets to do all this:
**thought**: it might be worth mentioning that the github terraform module can set 3 of the 4 of these things.

FYI 

- the identity provider handles the identity federation between github and gcp.
- the service account defines the gcp permissions allowed by the github action.
- and the project id tells gcp where the work should be done
- I'm unclear about the storage. Logs or something?

2024-08-16 23:04 UTC, steveoh commented on README.md
> +You can parameterize your function to do different things depending on the schedule that calls it. The `message-body` parameter of the schedule is available to the `subscribe` function in `main.py`.
```suggestion
You can parameterize your function to do perform different actions depending on the schedule that calls it. The `message-body` parameter of the PubSub topic schedule is available to the `subscribe` function in `main.py`. Therefore, you can create multiple schedules with different `message-body` values and switch the skid functionality based on the values. One example is to have a main routine that executes on a regular basis, and a utility routine that runs a couple times a year.
```

2024-08-16 23:06 UTC, steveoh submitted a review, later dismissed
looks great. I added a few suggestions that hopefully improve the documentation.

2024-08-19 14:37 UTC, jacobdadams commented on README.md
> +The cloud functions may need 512 MB or 1 GB of RAM to run successfully. The source dir should point to `src/skidname`. A cloud function just runs the specified function in the `main.py` file in the s
You're correct, it depends on the memory used by the dataframes, which will vary based on the geometry type and dataframe size. I like your changes, but I also want to keep the 512/1GB in there as a starting point for future me when I forget what I've done before. I'll blend your suggestion in.

2024-08-19 15:17 UTC, stdavis requested changes

2024-08-19 15:17 UTC, stdavis commented on .github/workflows/release.yml
> +    runs-on: ubuntu-latest
```suggestion
    runs-on: ubuntu-latest
    needs: deploy-prod
```

You only want this to run if the deploy was successful.

2024-08-19 15:17 UTC, stdavis commented on src/skidname/requirements.txt
These don't match what's in setup.py. You also may want to add a comment here and in setup.py to remind forgetful folks like me that they need to be kept in sync.

2024-08-19 15:18 UTC, steveoh commented on README.md
> +The cloud functions may need 512 MB or 1 GB of RAM to run successfully. The source dir should point to `src/skidname`. A cloud function just runs the specified function in the `main.py` file in the s
Ok. If you want to keep those numbers in there can you provide some context to the data frame size that may help owners choose a starting value?

My suggestion to find the right size would be to run with a gig, look at the resource usage, and adjust until it's the right size. 

Since these values determine the cost of the skid, it'd be nice to steer users to finding the right size.

2024-08-20 21:09 UTC, steveoh commented on README.md
> +The cloud functions may need 512 MB or 1 GB of RAM to run successfully. The source dir should point to `src/skidname`. A cloud function just runs the specified function in the `main.py` file in the s
That's pretty much sums up my reasoning to replace the suggestions.

2024-08-20 21:10 UTC, steveoh commented on src/skidname/requirements.txt
https://github.com/agrc/skid/issues/27

2025-02-07 19:23 UTC, stdavis commented
Much of this was taken care of in #31. There may be some readme stuff that you still want to merge in this PR.

2025-03-07 00:38 UTC, steveoh commented
i believe this is outdated and no longer relevant.

2025-03-07 00:38 UTC, closed without merging